=== savinov-vy/webservice/src/main/xsd/requestLoan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="requestLoan">
       <xsd:complexType>
           <xsd:sequence>
               <xsd:element name="personData" type="personData"/>
               <xsd:element name="deatailsLoan" type="deatailsLoan"/>
           </xsd:sequence>
       </xsd:complexType>
   </xsd:element>
    
    <xsd:complexType name="personData">
        <xsd:sequence>

            <xsd:element name="lastname">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z]{2,40}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="firstname">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z]{2,40}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="patronymic">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[a-zA-Z]{0,40}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="sex">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="1"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="dateOfBirth" type="xsd:date"/>

            <xsd:element name="passportSeries">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[0-9]{4}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="passportNumber">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[0-9]{6}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="deatailsLoan">
        <xsd:sequence>
            <xsd:element name="amountOfCredit">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                    <xsd:minInclusive value="0"/>
                    <xsd:fractionDigits value="2"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="timeCredit">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="availabilityOfInsurance" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== savinov-vy/webservice/src/main/xml/requestLoan.xml
<?xml version="1.0" encoding="UTF-8"?>
<requestLoan xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="../xsd/requestLoan.xsd">
<personData>
    <lastname>ffg</lastname>
    <firstname>Fsfgsdf</firstname>
    <patronymic></patronymic>
    <sex>1</sex>
    <dateOfBirth>1988-12-20</dateOfBirth>
    <passportSeries>5526</passportSeries>
    <passportNumber>546464</passportNumber>
</personData>
    <deatailsLoan>
        <amountOfCredit>5.32</amountOfCredit>
        <timeCredit>2</timeCredit>
        <availabilityOfInsurance>false</availabilityOfInsurance>
    </deatailsLoan>
</requestLoan>
